x = int(input("Write the first number: "))
y = int(input("Write the second number: "))

print("x is equal to y?")
print(x == y)
print("x is not equal to y?")
print(x != y)
print("x is greater than y?")
print(x > y)
print("x is less than y?")
print(x < y)
print("x is greater than or equal to y?")
print(x >= y)
print("x is less than or equal to y?")
print(x <= y)